### ISSUE TITLE
Не находит шрифты

### ISSUE THREAD

**Issue by snpefk** [barsoosayque/opensi#10]
```
Failed to load font "rubik.ttf" (failed to create the font face)
```

**Comment by barsoosayque** [comment]
```sh
$ cd resource
$ ../build/opensi
```
?

**Comment by snpefk** [comment]
Робит, но почему так?

**Comment by barsoosayque** [comment]
Потому что я сделал так, что все ресурсы должны лежать в working directory.
Впринципе, надо поменять все `loadFromFile` с `file.extension` на `resource/file.extension`.
