### ISSUE TITLE
Code style 

### ISSUE THREAD

**Issue by snpefk** [barsoosayque/opensi#2]
Заметил венгерскую нотацию в `scene_manager.hpp`. 
Есть еще какие-то правила (или лушче линк на правила) о которых нужно знать?

**Comment by barsoosayque** [comment]
- Мемберы классов и структур имеют префикс `m_`, все остальное без них;
- Snake case.

Остальное как хочешь, я хотел настроить clang-format синтаксиса чуть по-позже.

**Comment by snpefk** [comment]
А на CI проверки не идут?
