### ISSUE TITLE
Поставить на рельсы CI

### ISSUE THREAD

**Issue by barsoosayque** [barsoosayque/opensi#3]
С помощью Travis или Appveyor установить билд на все три системы: Windows, Linux и Mac.

**Comment by snpefk** [comment]
А Mac кто проверять будет?

**Comment by barsoosayque** [comment]
Главное чтобы собиралось

**Comment by snpefk** [comment]
А может будем постепенно? Давай с Linux начнём.

**Comment by barsoosayque** [comment]
> А может будем постепенно? Давай с Linux начнём.

Я уже завел на Linux gcc/clang, и сегодня смог завести на OSX clang.
Так же я разобрался в проблеме почему Windows vs19 падает, и скоро заведу и его.
